module Redenik::SystemData
	TILESIZE = 32
	ICONSIZE = 32

	DEFAULT_GFXWIDTH 				= 816
	DEFAULT_GFXHEIGHT 				= 624
	DEFAULT_GFXFULL 				= true
	DEFAULT_ENABLED_LETTER_HOTKEYS 	= true
	DEFAULT_ENABLED_NOUSE 			= true
	
end